
## Coding - Sasha

In [ ]:
import pandas as pd

movies = pd.read_csv('imdb_top_1000.csv')

In [ ]:
movies

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,15,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,15,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,12,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,15,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,PG,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,PG,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,PG,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,30500000.0
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,PG,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,PG,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [ ]:
!pip install unidecode
# !pip install langdetect

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: unidecode in /usr/local/lib/python3.9/dist-packages (1.3.6)

In [ ]:
from langdetect import detect

def df_detect(word):
  try:
    return detect(word)
  except:
    return 'nu'

movie_language = movies.Series_Title.apply(df_detect)

ModuleNotFoundError: ignored

In [ ]:
import nltk

nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/bllip_wsj_no_aux.zip.
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/book_grammars.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/chat80.zip.
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/city_database.zip.
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/comparative_sentences.zip.
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2000.zip.
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2002.zip.
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/crubadan.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dependency_treebank.zip.
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dolch.zip.
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/europarl_raw.zip.
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/floresta.zip.
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v15.zip.
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v17.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ieer.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/indian.zip.
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/kimmo.zip.
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/large_grammars.zip.
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/lin_thesaurus.zip.
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mac_morpho.zip.
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/maxent_treebank_pos_tagger.zip.
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/moses_sample.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mte_teip5.zip.
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Unzipping misc/mwa_ppdb.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nonbreaking_prefixes.zip.
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nps_chat.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/opinion_lexicon.zip.
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/paradigms.zip.
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pe08.zip.
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping misc/perluniprops.zip.
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pil.zip.
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pl196x.zip.
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/porter_test.zip.
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ppattach.zip.
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/problem_reports.zip.
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_1.zip.
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_2.zip.
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pros_cons.zip.
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ptb.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/qc.zip.
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/rslp.zip.
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/rte.zip.
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/sample_grammars.zip.
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/senseval.zip.
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentence_polarity.zip.
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentiwordnet.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sinica_treebank.zip.
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/smultron.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/spanish_grammars.zip.
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/state_union.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/subjectivity.zip.
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/swadesh.zip.
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/switchboard.zip.
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets.zip.
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/timit.zip.
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/toolbox.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr.zip.
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr2.zip.
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/unicode_samples.zip.
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/universal_tagset.zip.
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet.zip.
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet3.zip.
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/webtext.zip.
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Unzipping models/wmt15_eval.zip.
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/word2vec_sample.zip.
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2022 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet2022.zip.
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ycoe.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection all

True

In [ ]:
def min_max_scaler(number_list):
  min, max = number_list.min(), number_list.max()
  diff = max-min
  result = []
  for i in number_list:
    result.append((i-min)/diff)
  return result

In [ ]:
from unidecode import unidecode
import nltk
import string
from sklearn.preprocessing import MinMaxScaler

stopwords = set(nltk.corpus.stopwords.words('english'))

def series_title_tokenize(sentence):
  sentence = nltk.word_tokenize(unidecode(sentence.lower()))
  return [word for word in sentence if word not in stopwords and word not in string.punctuation]

def nltk_pos_tagger(nltk_tag):
    if nltk_tag.startswith('J'):
        return nltk.corpus.wordnet.ADJ
    elif nltk_tag.startswith('V'):
        return nltk.corpus.wordnet.VERB
    elif nltk_tag.startswith('N'):
        return nltk.corpus.wordnet.NOUN
    elif nltk_tag.startswith('R'):
        return nltk.corpus.wordnet.ADV
    else:
        return None

def overview_tokenize(sentence):
  sentence = nltk.word_tokenize(sentence)
  tags = [(unidecode(i[0].lower()),nltk_pos_tagger(i[1])) for i in nltk.pos_tag(sentence)]
  tags = [i for i in tags if i[0] not in stopwords and i[0] not in string.punctuation]
  lemmatizer = nltk.stem.WordNetLemmatizer()
  result = []
  for i in tags:
    if i[1]:
      result.append(lemmatizer.lemmatize(i[0], i[1]))
    else:
      result.append(i[0])
  return result

certificate_dict = {'U':0,'PG':0.2,'12A':0.4,'12':0.6,'15':0.8,'18':1}
movies_search = movies.copy()
movies_search.Series_Title = movies_search.Series_Title.apply(series_title_tokenize)
movies_search.Overview = movies_search.Overview.apply(overview_tokenize)
movies_search.Released_Year = min_max_scaler(movies_search.Released_Year)
movies_search.Runtime = movies_search.Runtime.apply(lambda x: int(x.replace(' min', '')))
movies_search.Runtime = min_max_scaler(movies_search.Runtime)
movies_search.Certificate = movies_search.Certificate.replace(certificate_dict)
movies_search.Genre = movies_search.Genre.apply(lambda x: set(x.split(', ')))
#movies_search.insert(2,'Language',movie_language)
movies_search.insert(11,'Stars',movies_search.apply(lambda x: {x.Star1,x.Star2,x.Star3,x.Star4}, axis=1))
movies_search = movies_search.drop(['Poster_Link','Meta_score','Gross','Star1','Star2','Star3','Star4','IMDB_Rating','No_of_Votes'],axis=1)

In [ ]:
import numpy as np
from numpy.linalg import norm

def cosine_similarity(x,y):
  return np.dot(x,y)/(norm(x)*norm(y))

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(analyzer=lambda x: x)
overview_vectorized = vectorizer.fit_transform(movies_search.Overview)
tfidf_overview = pd.DataFrame(overview_vectorized.toarray())
tfidf_overview = tfidf_overview.astype(str).agg(', '.join, axis=1)
tfidf_overview = tfidf_overview.apply(lambda x: list(map(float, list(x.split(', ')))))
movies_search.Overview = tfidf_overview

series_title_vectorized = vectorizer.fit_transform(movies_search.Series_Title)
tfidf_series_title = pd.DataFrame(series_title_vectorized.toarray())
tfidf_series_title = tfidf_series_title.astype(str).agg(', '.join, axis=1)
tfidf_series_title = tfidf_series_title.apply(lambda x: list(map(float, list(x.split(', ')))))
movies_search.Series_Title = tfidf_series_title

In [ ]:
def number_change(number1,number2):
  return 1-abs(number1-number2)

def director_match(query,document):
  if query == document:
    return 1
  return 0

def stars_match(query,document):
  n = 0
  for i in query:
    if i in document:
      n+=1
  return n/4

def genre_match(query,document):
  n = 0
  length = len(query)
  for i in query:
    if i in document:
      n+=1
  return n/length

def find_titles(query):
  query = series_title_tokenize(query)
  query = vectorizer.transform([query]).todense()
  titles = movies_search.Series_Title.apply(lambda x: cosine_similarity(query,x)[0,0])
  title = titles.idxmax()
  return movies_search.iloc[title]

def evaluate(query,row):
  title_score = cosine_similarity(query.Series_Title,row.Series_Title)
  year_score = number_change(query.Released_Year,row.Released_Year)
  age_score = number_change(query.Certificate,row.Certificate)
  time_score = number_change(query.Runtime,row.Runtime)
  genre_score = genre_match(query.Genre,row.Genre)
  overview_score = cosine_similarity(query.Overview,row.Overview)
  director_score = director_match(query.Director,row.Director)
  stars_score = stars_match(query.Stars,row.Stars)
  return title_score+year_score+age_score+time_score+genre_score+overview_score+director_score+stars_score

def search(query):
  try:
    query = find_titles(query)
    search_index = movies_search.apply(lambda x: evaluate(query,x),axis=1).sort_values(ascending=False).index.values
    return movies.iloc[search_index]
  except:
    return 'No matches'

In [ ]:
search('shawshank')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,15,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0
25,https://m.media-amazon.com/images/M/MV5BMTUxMz...,The Green Mile,1999,18,189 min,"Crime, Drama, Fantasy",8.6,The lives of guards on Death Row are affected ...,61.0,Frank Darabont,Tom Hanks,Michael Clarke Duncan,David Morse,Bonnie Hunt,1147794,136801374.0
505,https://m.media-amazon.com/images/M/MV5BMTIzND...,Mystic River,2003,15,138 min,"Crime, Drama, Mystery",7.9,The lives of three men who were childhood frie...,84.0,Clint Eastwood,Sean Penn,Tim Robbins,Kevin Bacon,Emmy Rossum,419420,90135191.0
167,https://m.media-amazon.com/images/M/MV5BODM3YW...,Unforgiven,1992,15,130 min,"Drama, Western",8.2,Retired Old West gunslinger William Munny relu...,85.0,Clint Eastwood,Clint Eastwood,Gene Hackman,Morgan Freeman,Richard Harris,375935,101157447.0
673,https://m.media-amazon.com/images/M/MV5BODhlNj...,Glory,1989,15,122 min,"Biography, Drama, History",7.8,Robert Gould Shaw leads the U.S. Civil War's f...,78.0,Edward Zwick,Matthew Broderick,Denzel Washington,Cary Elwes,Morgan Freeman,122779,26830000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
query = movies_search.iloc[0]
search_index = movies_search.apply(lambda x: evaluate(query,x),axis=1).sort_values(ascending=False).index.values
movies.iloc[search_index]

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,15,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0
25,https://m.media-amazon.com/images/M/MV5BMTUxMz...,The Green Mile,1999,18,189 min,"Crime, Drama, Fantasy",8.6,The lives of guards on Death Row are affected ...,61.0,Frank Darabont,Tom Hanks,Michael Clarke Duncan,David Morse,Bonnie Hunt,1147794,136801374.0
505,https://m.media-amazon.com/images/M/MV5BMTIzND...,Mystic River,2003,15,138 min,"Crime, Drama, Mystery",7.9,The lives of three men who were childhood frie...,84.0,Clint Eastwood,Sean Penn,Tim Robbins,Kevin Bacon,Emmy Rossum,419420,90135191.0
167,https://m.media-amazon.com/images/M/MV5BODM3YW...,Unforgiven,1992,15,130 min,"Drama, Western",8.2,Retired Old West gunslinger William Munny relu...,85.0,Clint Eastwood,Clint Eastwood,Gene Hackman,Morgan Freeman,Richard Harris,375935,101157447.0
673,https://m.media-amazon.com/images/M/MV5BODhlNj...,Glory,1989,15,122 min,"Biography, Drama, History",7.8,Robert Gould Shaw leads the U.S. Civil War's f...,78.0,Edward Zwick,Matthew Broderick,Denzel Washington,Cary Elwes,Morgan Freeman,122779,26830000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
# Transforming query to vector

import re

query = 'the Shawshank redemption'

# remove leading articles
query = re.sub(r'^the ', '', query, flags=re.IGNORECASE)

# split query into words
words = query.split()

# convert each word to lowercase
words = [word.lower() for word in words]

print(words)

['shawshank', 'redemption']

## Coding - Valentina

- use boolean model
- AND and OR queries 
- how do make the search engine  unique?
- semantics films

In [ ]:
### Indexing - queries set

In [ ]:
import pandas as pd

In [ ]:

# Queries to be indexed

simple_queries = ['best rated movies of all time',
                  'worst rated movies of all time',
                  'movies with most votes',
                  'best movies from 1999 over two hours',
                  'biography and history movies',
                  'movies that have made the most money',
                  'worst comedy movies',
                  'movies from the 2000s',
                  'adeventure and action movies',
                  'horror and thriller movies',
                  'best rated animation movies',
                  'sci-fi and fantasy movies',
                  'best biography and fantasy movies',
                  'superhero movies',
                  'family friendly movies',
                  'best mistery and adventure movies',
                  'music and dance films',
                  'rom-com movies',
                  'book-to-film movies',
                  'asian movies',
                  'romantic movies',
                  'best british movies']

query_terms = [query.split(' ') for query in simple_queries]

query_terms

[['best', 'rated', 'movies', 'of', 'all', 'time'],
 ['worst', 'rated', 'movies', 'of', 'all', 'time'],
 ['movies', 'with', 'most', 'votes'],
 ['best', 'movies', 'from', '1999', 'over', 'two', 'hours'],
 ['biography', 'and', 'history', 'movies'],
 ['movies', 'that', 'have', 'made', 'the', 'most', 'money'],
 ['worst', 'comedy', 'movies'],
 ['movies', 'from', 'the', '2000s'],
 ['adeventure', 'and', 'action', 'movies'],
 ['horror', 'and', 'thriller', 'movies'],
 ['best', 'rated', 'animation', 'movies'],
 ['sci-fi', 'and', 'fantasy', 'movies'],
 ['best', 'biography', 'and', 'fantasy', 'movies'],
 ['superhero', 'movies'],
 ['family', 'friendly', 'movies'],
 ['best', 'mistery', 'and', 'adventure', 'movies'],
 ['music', 'and', 'dance', 'films'],
 ['rom-com', 'movies'],
 ['book-to-film', 'movies'],
 ['asian', 'movies'],
 ['romantic', 'movies'],
 ['best', 'british', 'movies']]

In [ ]:
# Queries vocabulary set

vocabulary = set()

for query in simple_queries:
  for word in query.split():
    vocabulary.add(word)

vocabulary = list(vocabulary)

vocabulary

['money',
 'worst',
 'most',
 'mistery',
 'over',
 'dance',
 'sci-fi',
 '2000s',
 'made',
 'films',
 'comedy',
 'thriller',
 'with',
 'movies',
 'fantasy',
 'book-to-film',
 'best',
 'rom-com',
 'from',
 'action',
 'friendly',
 'votes',
 'all',
 'romantic',
 'animation',
 'that',
 'superhero',
 'family',
 'time',
 'british',
 'and',
 'history',
 'rated',
 'asian',
 'adventure',
 'of',
 'two',
 'horror',
 'music',
 'the',
 'have',
 '1999',
 'adeventure',
 'biography',
 'hours']

In [ ]:
## Chat GPT code

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from flask import Flask, request, render_template

# Load the movie data into a Pandas dataframe
movies_df = pd.read_csv('imdb_top_1000.csv')

# Define a TF-IDF vectorizer with English stop words
vectorizer = TfidfVectorizer(stop_words='english')

# Vectorize the movie descriptions
vectorized_descriptions = vectorizer.fit_transform(movies_df['Overview'].values.astype('U'))

# Initialize a Flask app
app = Flask(__name__)

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/search', methods=['GET', 'POST'])
def search():
    query = request.form['query']
    if query:
        # Vectorize the query
        vectorized_query = vectorizer.transform([query])

        # Calculate the cosine similarities between the query and the movies
        similarities = cosine_similarity(vectorized_query, vectorized_descriptions).flatten()

        # Sort the movies by their similarity to the query
        movie_indices = similarities.argsort()[::-1]
        movie_titles = [movies_df['Series_title'][i] for i in movie_indices]
        movie_descriptions = [movies_df['Overview'][i] for i in movie_indices]
        movie_posters = [movies_df['Poster_Link'][i] for i in movie_indices]

        # Render the search results template with the top 10 movies
        return render_template('search_results.html', query=query, movie_titles=movie_titles[:10], movie_descriptions=movie_descriptions[:10], movie_posters=movie_posters[:10])
    else:
        return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)

 * Serving Flask app '__main__'
 * Debug mode: on

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug: * Restarting with stat

In [ ]:
import re

def extract_query_info(query):
    query_info = {}
    
    # Extract genres
    genre_pattern = re.compile(r'\b([\w-]+)(?:(?: and|,) ([\w-]+))? movies\b', re.IGNORECASE)
    genre_match = genre_pattern.search(query)
    if genre_match:
        genres = set()
        genres.add(genre_match.group(1).capitalize())
        if genre_match.group(2):
            genres.add(genre_match.group(2).capitalize())
        query_info['Genre'] = genres
    
    # Extract release year
    year_pattern = re.compile(r'\b(\d{4})\b')
    year_match = year_pattern.search(query)
    if year_match:
        query_info['Release_Year'] = {int(year_match.group(1))}
    
    return query_info

Testing for Subjective Evaluation

User feedback: Search by Title
- Nicola

Simple Queries

```
# This is formatted as code
```

In [ ]:
search('star wars') # no capital letters

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
29,https://m.media-amazon.com/images/M/MV5BNzVlY2...,Star Wars,1977,U,121 min,"Action, Adventure, Fantasy",8.6,Luke Skywalker joins forces with a Jedi Knight...,90.0,George Lucas,Mark Hamill,Harrison Ford,Carrie Fisher,Alec Guinness,1231473,322740140.0
109,https://m.media-amazon.com/images/M/MV5BOWZlMj...,Star Wars: Episode VI - Return of the Jedi,1983,U,131 min,"Action, Adventure, Fantasy",8.3,After a daring mission to rescue Han Solo from...,58.0,Richard Marquand,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,950470,309125409.0
16,https://m.media-amazon.com/images/M/MV5BYmU1ND...,Star Wars: Episode V - The Empire Strikes Back,1980,PG,124 min,"Action, Adventure, Fantasy",8.7,After the Rebels are brutally overpowered by t...,82.0,Irvin Kershner,Mark Hamill,Harrison Ford,Carrie Fisher,Billy Dee Williams,1159315,290475067.0
72,https://m.media-amazon.com/images/M/MV5BMjA0OD...,Raiders of the Lost Ark,1981,12A,115 min,"Action, Adventure",8.4,"In 1936, archaeologist and adventurer Indiana ...",85.0,Steven Spielberg,Harrison Ford,Karen Allen,Paul Freeman,John Rhys-Davies,884112,248159971.0
839,https://m.media-amazon.com/images/M/MV5BMzcyYW...,Star Trek II: The Wrath of Khan,1982,12A,113 min,"Action, Adventure, Sci-Fi",7.7,"With the assistance of the Enterprise crew, Ad...",67.0,Nicholas Meyer,William Shatner,Leonard Nimoy,DeForest Kelley,James Doohan,112704,78912963.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Lion King') #instead of (The) Lion King

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
43,https://m.media-amazon.com/images/M/MV5BYTYxNG...,The Lion King,1994,U,88 min,"Animation, Adventure, Drama",8.5,Lion prince Simba and his father are targeted ...,88.0,Roger Allers,Rob Minkoff,Matthew Broderick,Jeremy Irons,James Earl Jones,942045,422783777.0
672,https://m.media-amazon.com/images/M/MV5BOTc0OD...,Majo no takkyûbin,1989,U,103 min,"Animation, Adventure, Drama",7.8,"A young witch, on her mandatory year of indepe...",83.0,Hayao Miyazaki,Kirsten Dunst,Minami Takayama,Rei Sakuma,Kappei Yamaguchi,124193,NaN
956,https://m.media-amazon.com/images/M/MV5BODkxNG...,Mulan,1998,U,88 min,"Animation, Adventure, Family",7.6,"To save her father from death in the army, a y...",71.0,Tony Bancroft,Barry Cook,Ming-Na Wen,Eddie Murphy,BD Wong,256906,120620254.0
332,https://m.media-amazon.com/images/M/MV5BNThmMW...,Kaguyahime no monogatari,2013,U,137 min,"Animation, Adventure, Drama",8.0,Found inside a shining stalk of bamboo by an o...,89.0,Isao Takahata,Chloë Grace Moretz,James Caan,Mary Steenburgen,James Marsden,38746,1506975.0
986,https://m.media-amazon.com/images/M/MV5BMzZiOD...,Watership Down,1978,PG,91 min,"Animation, Adventure, Drama",7.6,Hoping to escape destruction by human develope...,64.0,Martin Rosen,John Hubley,John Hurt,Richard Briers,Ralph Richardson,33656,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search ('Jokr') #spelling mistake

'No matches'

In [ ]:
search ('Joker') #without spelling mistake

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
33,https://m.media-amazon.com/images/M/MV5BNGVjNW...,Joker,2019,15,122 min,"Crime, Drama, Thriller",8.5,"In Gotham City, mentally troubled comedian Art...",59.0,Todd Phillips,Joaquin Phoenix,Robert De Niro,Zazie Beetz,Frances Conroy,939252,335451311.0
474,https://m.media-amazon.com/images/M/MV5BN2U1Yz...,Nightcrawler,2014,15,117 min,"Crime, Drama, Thriller",7.9,"When Louis Bloom, a con man desperate for work...",76.0,Dan Gilroy,Jake Gyllenhaal,Rene Russo,Bill Paxton,Riz Ahmed,466134,32381218.0
527,https://m.media-amazon.com/images/M/MV5BYTVjYW...,The Untouchables,1987,15,119 min,"Crime, Drama, Thriller",7.9,During the era of Prohibition in the United St...,79.0,Brian De Palma,Kevin Costner,Sean Connery,Robert De Niro,Charles Martin Smith,281842,76270454.0
232,https://m.media-amazon.com/images/M/MV5BMjA5Nj...,No Country for Old Men,2007,15,122 min,"Crime, Drama, Thriller",8.1,Violence and mayhem ensue after a hunter stumb...,91.0,Ethan Coen,Joel Coen,Tommy Lee Jones,Javier Bardem,Josh Brolin,856916,74283625.0
938,https://m.media-amazon.com/images/M/MV5BMjA4Mj...,21 Grams,2003,15,124 min,"Crime, Drama, Thriller",7.6,A freak accident brings together a critically ...,70.0,Alejandro G. Iñárritu,Sean Penn,Benicio Del Toro,Naomi Watts,Danny Huston,224545,16290476.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search ('Infinity Stone')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
60,https://m.media-amazon.com/images/M/MV5BMjMxNj...,Avengers: Infinity War,2018,12,149 min,"Action, Adventure, Sci-Fi",8.4,The Avengers and their allies must be willing ...,68.0,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,834477,678815482.0
59,https://m.media-amazon.com/images/M/MV5BMTc5MD...,Avengers: Endgame,2019,12,181 min,"Action, Adventure, Drama",8.4,After the devastating events of Avengers: Infi...,78.0,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Evans,Mark Ruffalo,809955,858373000.0
583,https://m.media-amazon.com/images/M/MV5BMjQ0MT...,Captain America: Civil War,2016,12A,147 min,"Action, Adventure, Sci-Fi",7.8,Political involvement in the Avengers' affairs...,75.0,Anthony Russo,Joe Russo,Chris Evans,Robert Downey Jr.,Scarlett Johansson,663649,408084349.0
737,https://m.media-amazon.com/images/M/MV5BMzA2ND...,Captain America: The Winter Soldier,2014,12,136 min,"Action, Adventure, Sci-Fi",7.7,As Steve Rogers struggles to embrace his role ...,70.0,Anthony Russo,Joe Russo,Chris Evans,Samuel L. Jackson,Scarlett Johansson,736182,259766572.0
357,https://m.media-amazon.com/images/M/MV5BNDYxNj...,The Avengers,2012,12A,143 min,"Action, Adventure, Sci-Fi",8.0,Earth's mightiest heroes must come together an...,69.0,Joss Whedon,Robert Downey Jr.,Chris Evans,Scarlett Johansson,Jeremy Renner,1260806,623279547.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search ('avengers')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
357,https://m.media-amazon.com/images/M/MV5BNDYxNj...,The Avengers,2012,12A,143 min,"Action, Adventure, Sci-Fi",8.0,Earth's mightiest heroes must come together an...,69.0,Joss Whedon,Robert Downey Jr.,Chris Evans,Scarlett Johansson,Jeremy Renner,1260806,623279547.0
583,https://m.media-amazon.com/images/M/MV5BMjQ0MT...,Captain America: Civil War,2016,12A,147 min,"Action, Adventure, Sci-Fi",7.8,Political involvement in the Avengers' affairs...,75.0,Anthony Russo,Joe Russo,Chris Evans,Robert Downey Jr.,Scarlett Johansson,663649,408084349.0
60,https://m.media-amazon.com/images/M/MV5BMjMxNj...,Avengers: Infinity War,2018,12,149 min,"Action, Adventure, Sci-Fi",8.4,The Avengers and their allies must be willing ...,68.0,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Hemsworth,Mark Ruffalo,834477,678815482.0
634,https://m.media-amazon.com/images/M/MV5BOWE2MD...,Serenity,2005,15,119 min,"Action, Adventure, Sci-Fi",7.8,The crew of the ship Serenity try to evade an ...,74.0,Joss Whedon,Nathan Fillion,Gina Torres,Chiwetel Ejiofor,Alan Tudyk,283310,25514517.0
59,https://m.media-amazon.com/images/M/MV5BMTc5MD...,Avengers: Endgame,2019,12,181 min,"Action, Adventure, Drama",8.4,After the devastating events of Avengers: Infi...,78.0,Anthony Russo,Joe Russo,Robert Downey Jr.,Chris Evans,Mark Ruffalo,809955,858373000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search ('aladdin')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
399,https://m.media-amazon.com/images/M/MV5BY2Q2ND...,Aladdin,1992,PG,90 min,"Animation, Adventure, Comedy",8.0,A kindhearted street urchin and a power-hungry...,86.0,Ron Clements,John Musker,Scott Weinger,Robin Williams,Linda Larkin,373845,217350219.0
892,https://m.media-amazon.com/images/M/MV5BMjI4Mz...,Moana,2016,PG,107 min,"Animation, Adventure, Comedy",7.6,"In Ancient Polynesia, when a terrible curse in...",81.0,Ron Clements,John Musker,Don Hall,Chris Williams,Auli'i Cravalho,272784,248757044.0
976,https://m.media-amazon.com/images/M/MV5BN2JlZT...,The Little Mermaid,1989,U,83 min,"Animation, Family, Fantasy",7.6,A mermaid princess makes a Faustian bargain in...,88.0,Ron Clements,John Musker,Jodi Benson,Samuel E. Wright,Rene Auberjonois,237696,111543479.0
822,https://m.media-amazon.com/images/M/MV5BZjVkYm...,Kurenai no buta,1992,PG,94 min,"Animation, Adventure, Comedy",7.7,"In 1930s Italy, a veteran World War I pilot is...",83.0,Hayao Miyazaki,Shûichirô Moriyama,Tokiko Katô,Bunshi Katsura Vi,Tsunehiko Kamijô,77798,NaN
101,https://m.media-amazon.com/images/M/MV5BMDU2ZW...,Toy Story,1995,PG,81 min,"Animation, Adventure, Comedy",8.3,A cowboy doll is profoundly threatened and jea...,95.0,John Lasseter,Tom Hanks,Tim Allen,Don Rickles,Jim Varney,887429,191796233.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search ('toy story')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
101,https://m.media-amazon.com/images/M/MV5BMDU2ZW...,Toy Story,1995,PG,81 min,"Animation, Adventure, Comedy",8.3,A cowboy doll is profoundly threatened and jea...,95.0,John Lasseter,Tom Hanks,Tim Allen,Don Rickles,Jim Varney,887429,191796233.0
516,https://m.media-amazon.com/images/M/MV5BMWM5ZD...,Toy Story 2,1999,U,92 min,"Animation, Adventure, Comedy",7.9,"When Woody is stolen by a toy collector, Buzz ...",88.0,John Lasseter,Ash Brannon,Lee Unkrich,Tom Hanks,Tim Allen,527512,245852179.0
151,https://m.media-amazon.com/images/M/MV5BMTgxOT...,Toy Story 3,2010,U,103 min,"Animation, Adventure, Comedy",8.2,The toys are mistakenly delivered to a day-car...,92.0,Lee Unkrich,Tom Hanks,Tim Allen,Joan Cusack,Ned Beatty,757032,415004880.0
596,https://m.media-amazon.com/images/M/MV5BMTYzMD...,Toy Story 4,2019,U,100 min,"Animation, Adventure, Comedy",7.8,"When a new toy called ""Forky"" joins Woody and ...",84.0,Josh Cooley,Tom Hanks,Tim Allen,Annie Potts,Tony Hale,203177,434038008.0
399,https://m.media-amazon.com/images/M/MV5BY2Q2ND...,Aladdin,1992,PG,90 min,"Animation, Adventure, Comedy",8.0,A kindhearted street urchin and a power-hungry...,86.0,Ron Clements,John Musker,Scott Weinger,Robin Williams,Linda Larkin,373845,217350219.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('apocalypse')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
74,https://m.media-amazon.com/images/M/MV5BMDdhOD...,Apocalypse Now,1979,15,147 min,"Drama, Mystery, War",8.4,A U.S. Army officer serving in Vietnam is task...,94.0,Francis Ford Coppola,Martin Sheen,Marlon Brando,Robert Duvall,Frederic Forrest,606398,83471511.0
693,https://m.media-amazon.com/images/M/MV5BNzZlMT...,The Conversation,1974,12,113 min,"Drama, Mystery, Thriller",7.8,"A paranoid, secretive surveillance expert has ...",85.0,Francis Ford Coppola,Gene Hackman,John Cazale,Allen Garfield,Frederic Forrest,98611,4420000.0
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,15,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,15,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0
974,https://m.media-amazon.com/images/M/MV5BNWFlYW...,The Godfather: Part III,1990,15,162 min,"Crime, Drama",7.6,"Follows Michael Corleone, now in his 60s, as h...",60.0,Francis Ford Coppola,Al Pacino,Diane Keaton,Andy Garcia,Talia Shire,359809,66666062.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Aliens') #Relevance rank: 1

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
106,https://m.media-amazon.com/images/M/MV5BZGU2OG...,Aliens,1986,15,137 min,"Action, Adventure, Sci-Fi",8.3,Fifty-seven years after surviving an apocalypt...,84.0,James Cameron,Sigourney Weaver,Michael Biehn,Carrie Henn,Paul Reiser,652719,85160248.0
410,https://m.media-amazon.com/images/M/MV5BYTViNz...,The Terminator,1984,15,107 min,"Action, Sci-Fi",8.0,A human soldier is sent from 2029 to 1984 to s...,84.0,James Cameron,Arnold Schwarzenegger,Linda Hamilton,Michael Biehn,Paul Winfield,799795,38400000.0
44,https://m.media-amazon.com/images/M/MV5BMGU2Nz...,Terminator 2: Judgment Day,1991,15,137 min,"Action, Sci-Fi",8.5,"A cyborg, identical to the one who failed to k...",75.0,James Cameron,Arnold Schwarzenegger,Linda Hamilton,Edward Furlong,Robert Patrick,995506,204843350.0
623,https://m.media-amazon.com/images/M/MV5BMTYwOT...,Avatar,2009,12A,162 min,"Action, Adventure, Fantasy",7.8,A paraplegic Marine dispatched to the moon Pan...,83.0,James Cameron,Sam Worthington,Zoe Saldana,Sigourney Weaver,Michelle Rodriguez,1118998,760507625.0
677,https://m.media-amazon.com/images/M/MV5BY2QwYm...,Predator,1987,15,107 min,"Action, Adventure, Sci-Fi",7.8,A team of commandos on a mission in a Central ...,45.0,John McTiernan,Arnold Schwarzenegger,Carl Weathers,Kevin Peter Hall,Elpidia Carrillo,371387,59735548.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Scarface') #Relevance rank: 1

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
108,https://m.media-amazon.com/images/M/MV5BNjdjNG...,Scarface,1983,18,170 min,"Crime, Drama",8.3,"In 1980 Miami, a determined Cuban immigrant ta...",65.0,Brian De Palma,Al Pacino,Michelle Pfeiffer,Steven Bauer,Mary Elizabeth Mastrantonio,740911,45598982.0
523,https://m.media-amazon.com/images/M/MV5BN2I2N2...,Carlito's Way,1993,18,144 min,"Crime, Drama, Thriller",7.9,"A Puerto Rican former convict, just released f...",65.0,Brian De Palma,Al Pacino,Sean Penn,Penelope Ann Miller,John Leguizamo,201000,36948322.0
527,https://m.media-amazon.com/images/M/MV5BYTVjYW...,The Untouchables,1987,15,119 min,"Crime, Drama, Thriller",7.9,During the era of Prohibition in the United St...,79.0,Brian De Palma,Kevin Costner,Sean Connery,Robert De Niro,Charles Martin Smith,281842,76270454.0
849,https://m.media-amazon.com/images/M/MV5BYTU4ZT...,Serpico,1973,18,130 min,"Biography, Crime, Drama",7.7,An honest New York cop named Frank Serpico blo...,87.0,Sidney Lumet,Al Pacino,John Randolph,Jack Kehoe,Biff McGuire,109941,29800000.0
809,https://m.media-amazon.com/images/M/MV5BYzMzMD...,Donnie Brasco,1997,18,127 min,"Biography, Crime, Drama",7.7,An FBI undercover agent infiltrates the mob an...,76.0,Mike Newell,Al Pacino,Johnny Depp,Michael Madsen,Bruno Kirby,279318,41909762.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Taxi Driver') #Relevance rank: 1

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
111,https://m.media-amazon.com/images/M/MV5BM2M1Mm...,Taxi Driver,1976,18,114 min,"Crime, Drama",8.3,A mentally unstable veteran works as a nightti...,94.0,Martin Scorsese,Robert De Niro,Jodie Foster,Cybill Shepherd,Albert Brooks,724636,28262574.0
15,https://m.media-amazon.com/images/M/MV5BY2NkZj...,Goodfellas,1990,18,146 min,"Biography, Crime, Drama",8.7,The story of Henry Hill and his life in the mo...,90.0,Martin Scorsese,Robert De Niro,Ray Liotta,Joe Pesci,Lorraine Bracco,1020727,46836394.0
165,https://m.media-amazon.com/images/M/MV5BMTcxOW...,Casino,1995,18,178 min,"Crime, Drama",8.2,"A tale of greed, deception, money, power, and ...",73.0,Martin Scorsese,Robert De Niro,Sharon Stone,Joe Pesci,James Woods,466276,42438300.0
173,https://m.media-amazon.com/images/M/MV5BYjRmOD...,Raging Bull,1980,18,129 min,"Biography, Drama, Sport",8.2,"The life of boxer Jake LaMotta, whose violence...",89.0,Martin Scorsese,Robert De Niro,Cathy Moriarty,Joe Pesci,Frank Vincent,321860,23383987.0
836,https://m.media-amazon.com/images/M/MV5BMTUxMj...,After Hours,1985,15,97 min,"Comedy, Crime, Drama",7.7,An ordinary word processor has the worst night...,90.0,Martin Scorsese,Griffin Dunne,Rosanna Arquette,Verna Bloom,Tommy Chong,59635,10600000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('A clockwork orange') #Relevance rank: 1

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
113,https://m.media-amazon.com/images/M/MV5BMTY3Mj...,A Clockwork Orange,1971,18,136 min,"Crime, Drama, Sci-Fi",8.3,"In the future, a sadistic gang leader is impri...",77.0,Stanley Kubrick,Malcolm McDowell,Patrick Magee,Michael Bates,Warren Clarke,757904,6207725.0
73,https://m.media-amazon.com/images/M/MV5BZWFlYm...,The Shining,1980,15,146 min,"Drama, Horror",8.4,A family heads to an isolated hotel for the wi...,66.0,Stanley Kubrick,Jack Nicholson,Shelley Duvall,Danny Lloyd,Scatman Crothers,898237,44017374.0
104,https://m.media-amazon.com/images/M/MV5BNzkxOD...,Full Metal Jacket,1987,15,116 min,"Drama, War",8.3,A pragmatic U.S. Marine observes the dehumaniz...,76.0,Stanley Kubrick,Matthew Modine,R. Lee Ermey,Vincent D'Onofrio,Adam Baldwin,675146,46357676.0
281,https://m.media-amazon.com/images/M/MV5BNmY0MW...,Barry Lyndon,1975,12A,185 min,"Adventure, Drama, History",8.1,An Irish rogue wins the heart of a rich widow ...,89.0,Stanley Kubrick,Ryan O'Neal,Marisa Berenson,Patrick Magee,Hardy Krüger,149843,NaN
849,https://m.media-amazon.com/images/M/MV5BYTU4ZT...,Serpico,1973,18,130 min,"Biography, Crime, Drama",7.7,An honest New York cop named Frank Serpico blo...,87.0,Sidney Lumet,Al Pacino,John Randolph,Jack Kehoe,Biff McGuire,109941,29800000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('The wolf of wall street') #Relevance rank: 1

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
147,https://m.media-amazon.com/images/M/MV5BMjIxMj...,The Wolf of Wall Street,2013,18,180 min,"Biography, Crime, Drama",8.2,"Based on the true story of Jordan Belfort, fro...",75.0,Martin Scorsese,Leonardo DiCaprio,Jonah Hill,Margot Robbie,Matthew McConaughey,1187498,116900694.0
37,https://m.media-amazon.com/images/M/MV5BMTI1MT...,The Departed,2006,18,151 min,"Crime, Drama, Thriller",8.5,An undercover cop and a mole in the police att...,85.0,Martin Scorsese,Leonardo DiCaprio,Matt Damon,Jack Nicholson,Mark Wahlberg,1189773,132384315.0
15,https://m.media-amazon.com/images/M/MV5BY2NkZj...,Goodfellas,1990,18,146 min,"Biography, Crime, Drama",8.7,The story of Henry Hill and his life in the mo...,90.0,Martin Scorsese,Robert De Niro,Ray Liotta,Joe Pesci,Lorraine Bracco,1020727,46836394.0
484,https://m.media-amazon.com/images/M/MV5BMGUyM2...,The Irishman,2019,15,209 min,"Biography, Crime, Drama",7.9,An old man recalls his time painting houses fo...,94.0,Martin Scorsese,Robert De Niro,Al Pacino,Joe Pesci,Harvey Keitel,324720,7000000.0
165,https://m.media-amazon.com/images/M/MV5BMTcxOW...,Casino,1995,18,178 min,"Crime, Drama",8.2,"A tale of greed, deception, money, power, and ...",73.0,Martin Scorsese,Robert De Niro,Sharon Stone,Joe Pesci,James Woods,466276,42438300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Casino') #Relevance rank: 1

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
165,https://m.media-amazon.com/images/M/MV5BMTcxOW...,Casino,1995,18,178 min,"Crime, Drama",8.2,"A tale of greed, deception, money, power, and ...",73.0,Martin Scorsese,Robert De Niro,Sharon Stone,Joe Pesci,James Woods,466276,42438300.0
15,https://m.media-amazon.com/images/M/MV5BY2NkZj...,Goodfellas,1990,18,146 min,"Biography, Crime, Drama",8.7,The story of Henry Hill and his life in the mo...,90.0,Martin Scorsese,Robert De Niro,Ray Liotta,Joe Pesci,Lorraine Bracco,1020727,46836394.0
484,https://m.media-amazon.com/images/M/MV5BMGUyM2...,The Irishman,2019,15,209 min,"Biography, Crime, Drama",7.9,An old man recalls his time painting houses fo...,94.0,Martin Scorsese,Robert De Niro,Al Pacino,Joe Pesci,Harvey Keitel,324720,7000000.0
111,https://m.media-amazon.com/images/M/MV5BM2M1Mm...,Taxi Driver,1976,18,114 min,"Crime, Drama",8.3,A mentally unstable veteran works as a nightti...,94.0,Martin Scorsese,Robert De Niro,Jodie Foster,Cybill Shepherd,Albert Brooks,724636,28262574.0
147,https://m.media-amazon.com/images/M/MV5BMjIxMj...,The Wolf of Wall Street,2013,18,180 min,"Biography, Crime, Drama",8.2,"Based on the true story of Jordan Belfort, fro...",75.0,Martin Scorsese,Leonardo DiCaprio,Jonah Hill,Margot Robbie,Matthew McConaughey,1187498,116900694.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Jaws')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
415,https://m.media-amazon.com/images/M/MV5BMmVmOD...,Jaws,1975,12A,124 min,"Adventure, Thriller",8.0,When a killer shark unleashes chaos on a beach...,87.0,Steven Spielberg,Roy Scheider,Robert Shaw,Richard Dreyfuss,Lorraine Gary,543388,260000000.0
72,https://m.media-amazon.com/images/M/MV5BMjA0OD...,Raiders of the Lost Ark,1981,12A,115 min,"Action, Adventure",8.4,"In 1936, archaeologist and adventurer Indiana ...",85.0,Steven Spielberg,Harrison Ford,Karen Allen,Paul Freeman,John Rhys-Davies,884112,248159971.0
168,https://m.media-amazon.com/images/M/MV5BMjNkMz...,Indiana Jones and the Last Crusade,1989,12A,127 min,"Action, Adventure",8.2,"In 1938, after his father Professor Henry Jone...",65.0,Steven Spielberg,Harrison Ford,Sean Connery,Alison Doody,Denholm Elliott,692366,197171806.0
262,https://m.media-amazon.com/images/M/MV5BMjM2MD...,Jurassic Park,1993,PG,127 min,"Action, Adventure, Sci-Fi",8.1,A pragmatic paleontologist visiting an almost ...,68.0,Steven Spielberg,Sam Neill,Laura Dern,Jeff Goldblum,Richard Attenborough,867615,402453882.0
988,https://m.media-amazon.com/images/M/MV5BMjM1Nj...,Close Encounters of the Third Kind,1977,PG,138 min,"Drama, Sci-Fi",7.6,"Roy Neary, an electric lineman, watches how hi...",90.0,Steven Spielberg,Richard Dreyfuss,François Truffaut,Teri Garr,Melinda Dillon,184966,132088635.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Batman begins')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
155,https://m.media-amazon.com/images/M/MV5BOTY4Yj...,Batman Begins,2005,12,140 min,"Action, Adventure",8.2,"After training with his mentor, Batman begins ...",70.0,Christopher Nolan,Christian Bale,Michael Caine,Ken Watanabe,Liam Neeson,1308302,206852432.0
63,https://m.media-amazon.com/images/M/MV5BMTk4OD...,The Dark Knight Rises,2012,12,164 min,"Action, Adventure",8.4,Eight years after the Joker's reign of anarchy...,78.0,Christopher Nolan,Christian Bale,Tom Hardy,Anne Hathaway,Gary Oldman,1516346,448139099.0
8,https://m.media-amazon.com/images/M/MV5BMjAxMz...,Inception,2010,12,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,292576195.0
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,12,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0
36,https://m.media-amazon.com/images/M/MV5BMjA4ND...,The Prestige,2006,12,130 min,"Drama, Mystery, Sci-Fi",8.5,"After a tragic accident, two stage magicians e...",66.0,Christopher Nolan,Christian Bale,Hugh Jackman,Scarlett Johansson,Michael Caine,1190259,53089891.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('planet of the apes')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
426,https://m.media-amazon.com/images/M/MV5BMTg0Nj...,Planet of the Apes,1968,12,112 min,"Adventure, Sci-Fi",8.0,An astronaut crew crash-lands on a planet in t...,79.0,Franklin J. Schaffner,Charlton Heston,Roddy McDowall,Kim Hunter,Maurice Evans,165167,33395426.0
898,https://m.media-amazon.com/images/M/MV5BMTgwOD...,Dawn of the Planet of the Apes,2014,12,130 min,"Action, Adventure, Drama",7.6,A growing nation of genetically evolved apes l...,79.0,Matt Reeves,Gary Oldman,Keri Russell,Andy Serkis,Kodi Smit-McPhee,411599,208545589.0
542,https://m.media-amazon.com/images/M/MV5BMmNhZm...,Patton,1970,12,172 min,"Biography, Drama, War",7.9,The World War II phase of the career of contro...,91.0,Franklin J. Schaffner,George C. Scott,Karl Malden,Stephen Young,Michael Strong,93741,61700000.0
839,https://m.media-amazon.com/images/M/MV5BMzcyYW...,Star Trek II: The Wrath of Khan,1982,12A,113 min,"Action, Adventure, Sci-Fi",7.7,"With the assistance of the Enterprise crew, Ad...",67.0,Nicholas Meyer,William Shatner,Leonard Nimoy,DeForest Kelley,James Doohan,112704,78912963.0
807,https://m.media-amazon.com/images/M/MV5BZWFjYm...,The Fifth Element,1997,12,126 min,"Action, Adventure, Sci-Fi",7.7,"In the colorful future, a cab driver unwitting...",52.0,Luc Besson,Bruce Willis,Milla Jovovich,Gary Oldman,Ian Holm,434125,63540020.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Die Hard')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
171,https://m.media-amazon.com/images/M/MV5BZjRlND...,Die Hard,1988,15,132 min,"Action, Thriller",8.2,An NYPD officer tries to save his wife and sev...,72.0,John McTiernan,Bruce Willis,Alan Rickman,Bonnie Bedelia,Reginald VelJohnson,793164,83008852.0
963,https://m.media-amazon.com/images/M/MV5BZjI0ZW...,Die Hard: With a Vengeance,1995,15,128 min,"Action, Adventure, Thriller",7.6,John McClane and a Harlem store owner are targ...,58.0,John McTiernan,Bruce Willis,Jeremy Irons,Samuel L. Jackson,Graham Greene,364420,100012499.0
677,https://m.media-amazon.com/images/M/MV5BY2QwYm...,Predator,1987,15,107 min,"Action, Adventure, Sci-Fi",7.8,A team of commandos on a mission in a Central ...,45.0,John McTiernan,Arnold Schwarzenegger,Carl Weathers,Kevin Peter Hall,Elpidia Carrillo,371387,59735548.0
979,https://m.media-amazon.com/images/M/MV5BZTllNW...,Lethal Weapon,1987,15,109 min,"Action, Crime, Thriller",7.6,Two newly paired cops who are complete opposit...,68.0,Richard Donner,Mel Gibson,Danny Glover,Gary Busey,Mitchell Ryan,236894,65207127.0
275,https://m.media-amazon.com/images/M/MV5BNzQzMz...,Blade Runner,1982,15,117 min,"Action, Sci-Fi, Thriller",8.1,A blade runner must pursue and terminate four ...,84.0,Ridley Scott,Harrison Ford,Rutger Hauer,Sean Young,Edward James Olmos,693827,32868943.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Inside Out')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
213,https://m.media-amazon.com/images/M/MV5BOTgxMD...,Inside Out,2015,U,95 min,"Animation, Adventure, Comedy",8.1,After young Riley is uprooted from her Midwest...,94.0,Pete Docter,Ronnie Del Carmen,Amy Poehler,Bill Hader,Lewis Black,616228,356461711.0
245,https://m.media-amazon.com/images/M/MV5BMTY1NT...,"Monsters, Inc.",2001,U,92 min,"Animation, Adventure, Comedy",8.1,"In order to power the city, monsters have to s...",79.0,Pete Docter,David Silverman,Lee Unkrich,Billy Crystal,John Goodman,815505,289916256.0
205,https://m.media-amazon.com/images/M/MV5BZGE1MD...,Soul,2020,PG,100 min,"Animation, Adventure, Comedy",8.1,"After landing the gig of a lifetime, a New Yor...",83.0,Pete Docter,Kemp Powers,Jamie Foxx,Tina Fey,Graham Norton,159171,NaN
596,https://m.media-amazon.com/images/M/MV5BMTYzMD...,Toy Story 4,2019,U,100 min,"Animation, Adventure, Comedy",7.8,"When a new toy called ""Forky"" joins Woody and ...",84.0,Josh Cooley,Tom Hanks,Tim Allen,Annie Potts,Tony Hale,203177,434038008.0
756,https://m.media-amazon.com/images/M/MV5BOTc3Ym...,Gake no ue no Ponyo,2008,U,101 min,"Animation, Adventure, Comedy",7.7,A five-year-old boy develops a relationship wi...,86.0,Hayao Miyazaki,Cate Blanchett,Matt Damon,Liam Neeson,Tomoko Yamaguchi,125317,15090400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Spotlight')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
218,https://m.media-amazon.com/images/M/MV5BMjIyOT...,Spotlight,2015,15,129 min,"Biography, Crime, Drama",8.1,The true story of how the Boston Globe uncover...,93.0,Tom McCarthy,Mark Ruffalo,Michael Keaton,Rachel McAdams,Liev Schreiber,420316,45055776.0
916,https://m.media-amazon.com/images/M/MV5BMTIzNT...,The Visitor,2007,15,104 min,Drama,7.6,A college professor travels to New York City t...,79.0,Tom McCarthy,Richard Jenkins,Haaz Sleiman,Danai Gurira,Hiam Abbass,41544,9422422.0
937,https://m.media-amazon.com/images/M/MV5BMTUzND...,The Station Agent,2003,15,89 min,"Comedy, Drama",7.6,"When his only friend dies, a man born with dwa...",81.0,Tom McCarthy,Peter Dinklage,Patricia Clarkson,Bobby Cannavale,Paul Benjamin,67370,5739376.0
759,https://m.media-amazon.com/images/M/MV5BOTA1Mz...,Changeling,2008,15,141 min,"Biography, Crime, Drama",7.7,Grief-stricken mother Christine Collins (Angel...,63.0,Clint Eastwood,Angelina Jolie,Colm Feore,Amy Ryan,Gattlin Griffith,239203,35739802.0
263,https://m.media-amazon.com/images/M/MV5BMmYyOT...,In the Name of the Father,1993,15,133 min,"Biography, Crime, Drama",8.1,A man's coerced confession to an I.R.A. bombin...,84.0,Jim Sheridan,Daniel Day-Lewis,Pete Postlethwaite,Alison Crosbie,Philip King,156842,25010410.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Song of the Sea')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
219,https://m.media-amazon.com/images/M/MV5BMTQ2MD...,Song of the Sea,2014,PG,93 min,"Animation, Adventure, Drama",8.1,"Ben, a young Irish boy, and his little sister ...",85.0,Tomm Moore,David Rawle,Brendan Gleeson,Lisa Hannigan,Fionnula Flanagan,51679,857524.0
920,https://m.media-amazon.com/images/M/MV5BMjEzMj...,The Secret of Kells,2009,PG,71 min,"Animation, Adventure, Family",7.6,A young boy in a remote medieval outpost under...,81.0,Tomm Moore,Nora Twomey,Evan McGuire,Brendan Gleeson,Mick Lally,31779,686383.0
741,https://m.media-amazon.com/images/M/MV5BNjg0OT...,Le Petit Prince,2015,PG,108 min,"Animation, Adventure, Drama",7.7,A little girl lives in a very grown-up world w...,70.0,Mark Osborne,Jeff Bridges,Mackenzie Foy,Rachel McAdams,Marion Cotillard,56720,1339152.0
578,https://m.media-amazon.com/images/M/MV5BMjA2Mz...,Kubo and the Two Strings,2016,PG,101 min,"Animation, Action, Adventure",7.8,A young boy named Kubo must locate a magical s...,84.0,Travis Knight,Charlize Theron,Art Parkinson,Matthew McConaughey,Ralph Fiennes,118035,48023088.0
409,https://m.media-amazon.com/images/M/MV5BNTg0Nm...,Tenkû no shiro Rapyuta,1986,PG,125 min,"Animation, Adventure, Drama",8.0,A young boy and a girl with a magic crystal mu...,78.0,Hayao Miyazaki,Mayumi Tanaka,Keiko Yokozawa,Kotoe Hatsui,Minori Terada,150140,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Prisoners')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
222,https://m.media-amazon.com/images/M/MV5BMTg0NT...,Prisoners,2013,15,153 min,"Crime, Drama, Mystery",8.1,When Keller Dover's daughter and her friend go...,70.0,Denis Villeneuve,Hugh Jackman,Jake Gyllenhaal,Viola Davis,Melissa Leo,601149,61002302.0
340,https://m.media-amazon.com/images/M/MV5BNzA1Nj...,Blade Runner 2049,2017,15,164 min,"Action, Drama, Mystery",8.0,Young Blade Runner K's discovery of a long-bur...,81.0,Denis Villeneuve,Harrison Ford,Ryan Gosling,Ana de Armas,Dave Bautista,461823,92054159.0
90,https://m.media-amazon.com/images/M/MV5BMWE3MG...,Incendies,2010,15,131 min,"Drama, Mystery, War",8.3,Twins journey to the Middle East to discover t...,80.0,Denis Villeneuve,Lubna Azabal,Mélissa Désormeaux-Poulin,Maxim Gaudette,Mustafa Kamel,150023,6857096.0
893,https://m.media-amazon.com/images/M/MV5BMjA5Nj...,Sicario,2015,15,121 min,"Action, Crime, Drama",7.6,An idealistic FBI agent is enlisted by a gover...,82.0,Denis Villeneuve,Emily Blunt,Josh Brolin,Benicio Del Toro,Jon Bernthal,371291,46889293.0
767,https://m.media-amazon.com/images/M/MV5BN2UwND...,Zodiac,2007,15,157 min,"Crime, Drama, Mystery",7.7,"In the late 1960s/early 1970s, a San Francisco...",78.0,David Fincher,Jake Gyllenhaal,Robert Downey Jr.,Mark Ruffalo,Anthony Edwards,466080,33080084.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Harry Potter')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
781,https://m.media-amazon.com/images/M/MV5BMTI1ND...,Harry Potter and the Goblet of Fire,2005,12,157 min,"Adventure, Family, Fantasy",7.7,Harry Potter finds himself competing in a haza...,81.0,Mike Newell,Daniel Radcliffe,Emma Watson,Rupert Grint,Eric Sykes,548619,290013036.0
755,https://m.media-amazon.com/images/M/MV5BMTQ2OT...,Harry Potter and the Deathly Hallows: Part 1,2010,12,146 min,"Adventure, Family, Fantasy",7.7,"As Harry, Ron, and Hermione race against time ...",65.0,David Yates,Daniel Radcliffe,Emma Watson,Rupert Grint,Bill Nighy,479120,295983305.0
927,https://m.media-amazon.com/images/M/MV5BNzU3ND...,Harry Potter and the Half-Blood Prince,2009,12,153 min,"Action, Adventure, Family",7.6,As Harry Potter begins his sixth year at Hogwa...,78.0,David Yates,Daniel Radcliffe,Emma Watson,Rupert Grint,Michael Gambon,474827,301959197.0
506,https://m.media-amazon.com/images/M/MV5BMTY4NT...,Harry Potter and the Prisoner of Azkaban,2004,PG,142 min,"Adventure, Family, Fantasy",7.9,"Harry Potter, Ron and Hermione return to Hogwa...",82.0,Alfonso Cuarón,Daniel Radcliffe,Emma Watson,Rupert Grint,Richard Griffiths,552493,249358727.0
226,https://m.media-amazon.com/images/M/MV5BMGVmMW...,Harry Potter and the Deathly Hallows: Part 2,2011,12,130 min,"Adventure, Drama, Fantasy",8.1,"Harry, Ron, and Hermione search for Voldemort'...",85.0,David Yates,Daniel Radcliffe,Emma Watson,Rupert Grint,Michael Gambon,764493,381011219.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('How to train your dragon')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
230,https://m.media-amazon.com/images/M/MV5BMjA5ND...,How to Train Your Dragon,2010,PG,98 min,"Animation, Action, Adventure",8.1,A hapless young Viking who aspires to hunt dra...,75.0,Dean DeBlois,Chris Sanders,Jay Baruchel,Gerard Butler,Christopher Mintz-Plasse,666773,217581231.0
599,https://m.media-amazon.com/images/M/MV5BMzMwMT...,How to Train Your Dragon 2,2014,PG,102 min,"Animation, Action, Adventure",7.8,When Hiccup and Toothless discover an ice cave...,76.0,Dean DeBlois,Jay Baruchel,Cate Blanchett,Gerard Butler,Craig Ferguson,305611,177002924.0
592,https://m.media-amazon.com/images/M/MV5BMDliOT...,Big Hero 6,2014,PG,102 min,"Animation, Action, Adventure",7.8,A special bond develops between plus-sized inf...,74.0,Don Hall,Chris Williams,Ryan Potter,Scott Adsit,Jamie Chung,410983,222527828.0
578,https://m.media-amazon.com/images/M/MV5BMjA2Mz...,Kubo and the Two Strings,2016,PG,101 min,"Animation, Action, Adventure",7.8,A young boy named Kubo must locate a magical s...,84.0,Travis Knight,Charlize Theron,Art Parkinson,Matthew McConaughey,Ralph Fiennes,118035,48023088.0
389,https://m.media-amazon.com/images/M/MV5BMjIxND...,The Iron Giant,1999,PG,86 min,"Animation, Action, Adventure",8.0,A young boy befriends a giant robot from outer...,85.0,Brad Bird,Eli Marienthal,Harry Connick Jr.,Jennifer Aniston,Vin Diesel,172083,23159305.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Million Dollar Baby')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
234,https://m.media-amazon.com/images/M/MV5BMTkxNz...,Million Dollar Baby,2004,12,132 min,"Drama, Sport",8.1,A determined woman works with a hardened boxin...,86.0,Clint Eastwood,Hilary Swank,Clint Eastwood,Morgan Freeman,Jay Baruchel,635975,100492203.0
167,https://m.media-amazon.com/images/M/MV5BODM3YW...,Unforgiven,1992,15,130 min,"Drama, Western",8.2,Retired Old West gunslinger William Munny relu...,85.0,Clint Eastwood,Clint Eastwood,Gene Hackman,Morgan Freeman,Richard Harris,375935,101157447.0
965,https://m.media-amazon.com/images/M/MV5BNmRiZD...,The Bridges of Madison County,1995,12,135 min,"Drama, Romance",7.6,Photographer Robert Kincaid wanders into the l...,69.0,Clint Eastwood,Clint Eastwood,Meryl Streep,Annie Corley,Victor Slezak,73172,71516617.0
225,https://m.media-amazon.com/images/M/MV5BMTc5NT...,Gran Torino,2008,15,116 min,Drama,8.1,Disgruntled Korean War veteran Walt Kowalski s...,72.0,Clint Eastwood,Clint Eastwood,Bee Vang,Christopher Carley,Ahney Her,720450,148095302.0
505,https://m.media-amazon.com/images/M/MV5BMTIzND...,Mystic River,2003,15,138 min,"Crime, Drama, Mystery",7.9,The lives of three men who were childhood frie...,84.0,Clint Eastwood,Sean Penn,Tim Robbins,Kevin Bacon,Emmy Rossum,419420,90135191.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Catch me if you can')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
243,https://m.media-amazon.com/images/M/MV5BMTY5Mz...,Catch Me If You Can,2002,12,141 min,"Biography, Crime, Drama",8.1,"Barely 21 yet, Frank is a skilled forger who h...",75.0,Steven Spielberg,Leonardo DiCaprio,Tom Hanks,Christopher Walken,Martin Sheen,832846,164615351.0
890,https://m.media-amazon.com/images/M/MV5BMjIxOT...,Bridge of Spies,2015,12,142 min,"Drama, History, Thriller",7.6,"During the Cold War, an American lawyer is rec...",81.0,Steven Spielberg,Tom Hanks,Mark Rylance,Alan Alda,Amy Ryan,287659,72313754.0
951,https://m.media-amazon.com/images/M/MV5BZTI3Yz...,Minority Report,2002,12,145 min,"Action, Crime, Mystery",7.6,In a future where a special police unit is abl...,80.0,Steven Spielberg,Tom Cruise,Colin Farrell,Samantha Morton,Max von Sydow,508417,132072926.0
24,https://m.media-amazon.com/images/M/MV5BZjhkMD...,Saving Private Ryan,1998,15,169 min,"Drama, War",8.6,"Following the Normandy Landings, a group of U....",91.0,Steven Spielberg,Tom Hanks,Matt Damon,Tom Sizemore,Edward Burns,1235804,216540909.0
7,https://m.media-amazon.com/images/M/MV5BNDE4OT...,Schindler's List,1993,15,195 min,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,96898818.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Into The Wild')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
231,https://m.media-amazon.com/images/M/MV5BMTAwND...,Into the Wild,2007,15,148 min,"Adventure, Biography, Drama",8.1,"After graduating from Emory University, top st...",73.0,Sean Penn,Emile Hirsch,Vince Vaughn,Catherine Keener,Marcia Gay Harden,572921,18354356.0
638,https://m.media-amazon.com/images/M/MV5BOTNmZT...,Diarios de motocicleta,2004,15,126 min,"Adventure, Biography, Drama",7.8,The dramatization of a motorcycle road trip Ch...,75.0,Walter Salles,Gael García Bernal,Rodrigo De la Serna,Mía Maestro,Mercedes Morán,96703,16756372.0
361,https://m.media-amazon.com/images/M/MV5BZDMxOG...,Blood Diamond,2006,15,143 min,"Adventure, Drama, Thriller",8.0,"A fisherman, a smuggler, and a syndicate of bu...",64.0,Edward Zwick,Leonardo DiCaprio,Djimon Hounsou,Jennifer Connelly,Kagiso Kuypers,499439,57366262.0
779,https://m.media-amazon.com/images/M/MV5BMTQxND...,Ray,2004,15,152 min,"Biography, Drama, Music",7.7,The story of the life and career of the legend...,73.0,Taylor Hackford,Jamie Foxx,Regina King,Kerry Washington,Clifton Powell,138356,75331600.0
759,https://m.media-amazon.com/images/M/MV5BOTA1Mz...,Changeling,2008,15,141 min,"Biography, Crime, Drama",7.7,Grief-stricken mother Christine Collins (Angel...,63.0,Clint Eastwood,Angelina Jolie,Colm Feore,Amy Ryan,Gattlin Griffith,239203,35739802.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Monsters Inc')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
245,https://m.media-amazon.com/images/M/MV5BMTY1NT...,"Monsters, Inc.",2001,U,92 min,"Animation, Adventure, Comedy",8.1,"In order to power the city, monsters have to s...",79.0,Pete Docter,David Silverman,Lee Unkrich,Billy Crystal,John Goodman,815505,289916256.0
213,https://m.media-amazon.com/images/M/MV5BOTgxMD...,Inside Out,2015,U,95 min,"Animation, Adventure, Comedy",8.1,After young Riley is uprooted from her Midwest...,94.0,Pete Docter,Ronnie Del Carmen,Amy Poehler,Bill Hader,Lewis Black,616228,356461711.0
205,https://m.media-amazon.com/images/M/MV5BZGE1MD...,Soul,2020,PG,100 min,"Animation, Adventure, Comedy",8.1,"After landing the gig of a lifetime, a New Yor...",83.0,Pete Docter,Kemp Powers,Jamie Foxx,Tina Fey,Graham Norton,159171,NaN
516,https://m.media-amazon.com/images/M/MV5BMWM5ZD...,Toy Story 2,1999,U,92 min,"Animation, Adventure, Comedy",7.9,"When Woody is stolen by a toy collector, Buzz ...",88.0,John Lasseter,Ash Brannon,Lee Unkrich,Tom Hanks,Tim Allen,527512,245852179.0
242,https://m.media-amazon.com/images/M/MV5BZTAzNW...,Finding Nemo,2003,U,100 min,"Animation, Adventure, Comedy",8.1,After his son is captured in the Great Barrier...,90.0,Andrew Stanton,Lee Unkrich,Albert Brooks,Ellen DeGeneres,Alexander Gould,949565,380843261.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Jurrasic Park')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
262,https://m.media-amazon.com/images/M/MV5BMjM2MD...,Jurassic Park,1993,PG,127 min,"Action, Adventure, Sci-Fi",8.1,A pragmatic paleontologist visiting an almost ...,68.0,Steven Spielberg,Sam Neill,Laura Dern,Jeff Goldblum,Richard Attenborough,867615,402453882.0
168,https://m.media-amazon.com/images/M/MV5BMjNkMz...,Indiana Jones and the Last Crusade,1989,12A,127 min,"Action, Adventure",8.2,"In 1938, after his father Professor Henry Jone...",65.0,Steven Spielberg,Harrison Ford,Sean Connery,Alison Doody,Denholm Elliott,692366,197171806.0
72,https://m.media-amazon.com/images/M/MV5BMjA0OD...,Raiders of the Lost Ark,1981,12A,115 min,"Action, Adventure",8.4,"In 1936, archaeologist and adventurer Indiana ...",85.0,Steven Spielberg,Harrison Ford,Karen Allen,Paul Freeman,John Rhys-Davies,884112,248159971.0
832,https://m.media-amazon.com/images/M/MV5BMmQwNz...,Empire of the Sun,1987,PG,153 min,"Action, Drama, History",7.7,A young English boy struggles to survive under...,62.0,Steven Spielberg,Christian Bale,John Malkovich,Miranda Richardson,Nigel Havers,115677,22238696.0
988,https://m.media-amazon.com/images/M/MV5BMjM1Nj...,Close Encounters of the Third Kind,1977,PG,138 min,"Drama, Sci-Fi",7.6,"Roy Neary, an electric lineman, watches how hi...",90.0,Steven Spielberg,Richard Dreyfuss,François Truffaut,Teri Garr,Melinda Dillon,184966,132088635.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Stand By Me')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
267,https://m.media-amazon.com/images/M/MV5BODJmY2...,Stand by Me,1986,15,89 min,"Adventure, Drama",8.1,"After the death of one of his friends, a write...",75.0,Rob Reiner,Wil Wheaton,River Phoenix,Corey Feldman,Jerry O'Connell,363401,52287414.0
975,https://m.media-amazon.com/images/M/MV5BMjE0OD...,When Harry Met Sally...,1989,15,95 min,"Comedy, Drama, Romance",7.6,Harry and Sally have known each other for year...,76.0,Rob Reiner,Billy Crystal,Meg Ryan,Carrie Fisher,Bruno Kirby,195663,92823600.0
670,https://m.media-amazon.com/images/M/MV5BNzY0OD...,Misery,1990,15,107 min,"Drama, Thriller",7.8,After a famous author is rescued from a car cr...,75.0,Rob Reiner,James Caan,Kathy Bates,Richard Farnsworth,Frances Sternhagen,184740,61276872.0
824,https://m.media-amazon.com/images/M/MV5BMmRlZD...,A Few Good Men,1992,15,138 min,"Drama, Thriller",7.7,Military lawyer Lieutenant Daniel Kaffee defen...,62.0,Rob Reiner,Tom Cruise,Jack Nicholson,Demi Moore,Kevin Bacon,235388,141340178.0
530,https://m.media-amazon.com/images/M/MV5BMTQ2MT...,This Is Spinal Tap,1984,15,82 min,"Comedy, Music",7.9,"Spinal Tap, one of England's loudest bands, is...",92.0,Rob Reiner,Rob Reiner,Michael McKean,Christopher Guest,Kimberly Stringer,128812,188751.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Dead Poets Society')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
266,https://m.media-amazon.com/images/M/MV5BOGYwYW...,Dead Poets Society,1989,PG,128 min,"Comedy, Drama",8.1,Maverick teacher John Keating uses poetry to e...,79.0,Peter Weir,Robin Williams,Robert Sean Leonard,Ethan Hawke,Josh Charles,425457,95860116.0
250,https://m.media-amazon.com/images/M/MV5BMDIzOD...,The Truman Show,1998,PG,103 min,"Comedy, Drama",8.1,An insurance salesman discovers his whole life...,90.0,Peter Weir,Jim Carrey,Ed Harris,Laura Linney,Noah Emmerich,939631,125618201.0
26,https://m.media-amazon.com/images/M/MV5BYmJmM2...,La vita è bella,1997,PG,116 min,"Comedy, Drama, Romance",8.6,When an open-minded Jewish librarian and his s...,59.0,Roberto Benigni,Roberto Benigni,Nicoletta Braschi,Giorgio Cantarini,Giustino Durano,623629,57598247.0
660,https://m.media-amazon.com/images/M/MV5BODllYj...,The Sandlot,1993,PG,101 min,"Comedy, Drama, Family",7.8,"In the summer of 1962, a new kid in town is ta...",55.0,David Mickey Evans,Tom Guiry,Mike Vitar,Art LaFleur,Patrick Renna,78963,32416586.0
687,https://m.media-amazon.com/images/M/MV5BMTViNj...,The King of Comedy,1982,PG,109 min,"Comedy, Crime, Drama",7.8,Rupert Pupkin is a passionate yet unsuccessful...,73.0,Martin Scorsese,Robert De Niro,Jerry Lewis,Diahnne Abbott,Sandra Bernhard,88511,2500000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('The Thing')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
271,https://m.media-amazon.com/images/M/MV5BNGViZW...,The Thing,1982,18,109 min,"Horror, Mystery, Sci-Fi",8.1,A research team in Antarctica is hunted by a s...,57.0,John Carpenter,Kurt Russell,Wilford Brimley,Keith David,Richard Masur,371271,13782838.0
844,https://m.media-amazon.com/images/M/MV5BNzk1OG...,Halloween,1978,18,91 min,"Horror, Thriller",7.7,Fifteen years after murdering his sister on Ha...,87.0,John Carpenter,Donald Pleasence,Jamie Lee Curtis,Tony Moran,Nancy Kyes,233106,47000000.0
403,https://m.media-amazon.com/images/M/MV5BODA2Mj...,Do the Right Thing,1989,18,120 min,"Comedy, Drama",8.0,On the hottest day of the year on a street in ...,93.0,Spike Lee,Danny Aiello,Ossie Davis,Ruby Dee,Richard Edson,89429,27545445.0
943,https://m.media-amazon.com/images/M/MV5BYTFkM2...,28 Days Later...,2002,18,113 min,"Drama, Horror, Sci-Fi",7.6,"Four weeks after a mysterious, incurable virus...",73.0,Danny Boyle,Cillian Murphy,Naomie Harris,Christopher Eccleston,Alex Palmer,376853,45064915.0
932,https://m.media-amazon.com/images/M/MV5BMzQ2ZT...,Saw,2004,18,103 min,"Horror, Mystery, Thriller",7.6,Two strangers awaken in a room with no recolle...,46.0,James Wan,Cary Elwes,Leigh Whannell,Danny Glover,Ken Leung,379020,56000369.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Rocky')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
279,https://m.media-amazon.com/images/M/MV5BMTY5MD...,Rocky,1976,12A,120 min,"Drama, Sport",8.1,A small-time boxer gets a supremely rare chanc...,70.0,John G. Avildsen,Sylvester Stallone,Talia Shire,Burt Young,Carl Weathers,518546,117235247.0
434,https://m.media-amazon.com/images/M/MV5BNjhjOD...,The Hustler,1961,12,134 min,"Drama, Sport",8.0,An up-and-coming pool player plays a long-time...,90.0,Robert Rossen,Paul Newman,Jackie Gleason,Piper Laurie,George C. Scott,75067,8284000.0
894,https://m.media-amazon.com/images/M/MV5BNmZkYj...,Creed,2015,12,133 min,"Drama, Sport",7.6,The former World Heavyweight Champion Rocky Ba...,82.0,Ryan Coogler,Michael B. Jordan,Sylvester Stallone,Tessa Thompson,Phylicia Rashad,247666,109767581.0
915,https://m.media-amazon.com/images/M/MV5BMjEzOT...,The Blind Side,2009,12A,129 min,"Biography, Drama, Sport",7.6,"The story of Michael Oher, a homeless and trau...",53.0,John Lee Hancock,Quinton Aaron,Sandra Bullock,Tim McGraw,Jae Head,293266,255959475.0
144,https://m.media-amazon.com/images/M/MV5BMTk4OD...,Warrior,2011,12A,140 min,"Action, Drama, Sport",8.2,The youngest son of an alcoholic former boxer ...,71.0,Gavin O'Connor,Tom Hardy,Nick Nolte,Joel Edgerton,Jennifer Morrison,435950,13657115.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('La La Land')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
327,https://m.media-amazon.com/images/M/MV5BMzUzND...,La La Land,2016,12A,128 min,"Comedy, Drama, Music",8.0,"While navigating their careers in Los Angeles,...",94.0,Damien Chazelle,Ryan Gosling,Emma Stone,Rosemarie DeWitt,J.K. Simmons,505918,151101803.0
34,https://m.media-amazon.com/images/M/MV5BOTA5ND...,Whiplash,2014,15,106 min,"Drama, Music",8.5,A promising young drummer enrolls at a cut-thr...,88.0,Damien Chazelle,Miles Teller,J.K. Simmons,Melissa Benoist,Paul Reiser,717585,13092000.0
472,https://m.media-amazon.com/images/M/MV5BMjEzOD...,Sing Street,2016,12,106 min,"Comedy, Drama, Music",7.9,A boy growing up in Dublin during the 1980s es...,79.0,John Carney,Ferdia Walsh-Peelo,Aidan Gillen,Maria Doyle Kennedy,Jack Reynor,85109,3237118.0
86,https://m.media-amazon.com/images/M/MV5BZWZhMj...,Andhadhun,2018,12A,139 min,"Crime, Drama, Music",8.3,A series of mysterious events change the life ...,NaN,Sriram Raghavan,Ayushmann Khurrana,Tabu,Radhika Apte,Anil Dhawan,71875,1373943.0
923,https://m.media-amazon.com/images/M/MV5BOTBmZD...,La Vie En Rose,2007,12,140 min,"Biography, Drama, Music",7.6,Biopic of the iconic French singer Édith Piaf....,66.0,Olivier Dahan,Marion Cotillard,Sylvie Testud,Pascal Greggory,Emmanuelle Seigner,82781,10301706.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Her')

'No matches'

In [ ]:
search('Bohemian Rhapsody')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
342,https://m.media-amazon.com/images/M/MV5BMTA2ND...,Bohemian Rhapsody,2018,12,134 min,"Biography, Drama, Music",8.0,The story of the legendary British rock band Q...,49.0,Bryan Singer,Rami Malek,Lucy Boynton,Gwilym Lee,Ben Hardy,450349,216428042.0
479,https://m.media-amazon.com/images/M/MV5BZGIzNW...,X-Men: Days of Future Past,2014,12,132 min,"Action, Adventure, Sci-Fi",7.9,The X-Men send Wolverine to the past in a desp...,75.0,Bryan Singer,Patrick Stewart,Ian McKellen,Hugh Jackman,James McAvoy,659763,233921534.0
923,https://m.media-amazon.com/images/M/MV5BOTBmZD...,La Vie En Rose,2007,12,140 min,"Biography, Drama, Music",7.6,Biopic of the iconic French singer Édith Piaf....,66.0,Olivier Dahan,Marion Cotillard,Sylvie Testud,Pascal Greggory,Emmanuelle Seigner,82781,10301706.0
635,https://m.media-amazon.com/images/M/MV5BMjIyOT...,Walk the Line,2005,12,136 min,"Biography, Drama, Music",7.8,A chronicle of country music legend Johnny Cas...,72.0,James Mangold,Joaquin Phoenix,Reese Witherspoon,Ginnifer Goodwin,Robert Patrick,234207,119519402.0
770,https://m.media-amazon.com/images/M/MV5BNTEzOT...,Control,2007,15,122 min,"Biography, Drama, Music",7.7,"A profile of Ian Curtis, the enigmatic singer ...",78.0,Anton Corbijn,Sam Riley,Samantha Morton,Craig Parkinson,Alexandra Maria Lara,61609,871577.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Slumdog Millionaire')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
354,https://m.media-amazon.com/images/M/MV5BZmNjZW...,Slumdog Millionaire,2008,15,120 min,"Drama, Romance",8.0,A Mumbai teenager reflects on his life after b...,84.0,Danny Boyle,Loveleen Tandan,Dev Patel,Freida Pinto,Saurabh Shukla,798882,141319928.0
943,https://m.media-amazon.com/images/M/MV5BYTFkM2...,28 Days Later...,2002,18,113 min,"Drama, Horror, Sci-Fi",7.6,"Four weeks after a mysterious, incurable virus...",73.0,Danny Boyle,Cillian Murphy,Naomie Harris,Christopher Eccleston,Alex Palmer,376853,45064915.0
254,https://m.media-amazon.com/images/M/MV5BMzA5Zj...,Trainspotting,1996,18,93 min,Drama,8.1,"Renton, deeply immersed in the Edinburgh drug ...",83.0,Danny Boyle,Ewan McGregor,Ewen Bremner,Jonny Lee Miller,Kevin McKidd,634716,16501785.0
620,https://m.media-amazon.com/images/M/MV5BMGRiYj...,Atonement,2007,15,123 min,"Drama, Mystery, Romance",7.8,Thirteen-year-old fledgling writer Briony Tall...,85.0,Joe Wright,Keira Knightley,James McAvoy,Brenda Blethyn,Saoirse Ronan,251370,50927067.0
905,https://m.media-amazon.com/images/M/MV5BNDY2OT...,Hævnen,2010,15,118 min,"Drama, Romance",7.6,The lives of two Danish families cross each ot...,65.0,Susanne Bier,Mikael Persbrandt,Trine Dyrholm,Markus Rygaard,Wil Johnson,38491,1008098.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Black Swan')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
355,https://m.media-amazon.com/images/M/MV5BNzY2Nz...,Black Swan,2010,15,108 min,"Drama, Thriller",8.0,A committed dancer struggles to maintain her s...,79.0,Darren Aronofsky,Natalie Portman,Mila Kunis,Vincent Cassel,Winona Ryder,699673,106954678.0
489,https://m.media-amazon.com/images/M/MV5BMTc5Mj...,The Wrestler,2008,15,109 min,"Drama, Sport",7.9,"A faded professional wrestler must retire, but...",80.0,Darren Aronofsky,Mickey Rourke,Marisa Tomei,Evan Rachel Wood,Mark Margolis,289415,26236603.0
97,https://m.media-amazon.com/images/M/MV5BOTdiNz...,Requiem for a Dream,2000,18,102 min,Drama,8.3,The drug-induced utopias of four Coney Island ...,68.0,Darren Aronofsky,Ellen Burstyn,Jared Leto,Jennifer Connelly,Marlon Wayans,766870,3635482.0
778,https://m.media-amazon.com/images/M/MV5BNjk1Nz...,The Machinist,2004,15,101 min,"Drama, Thriller",7.7,An industrial worker who hasn't slept in a yea...,61.0,Brad Anderson,Christian Bale,Jennifer Jason Leigh,Aitana Sánchez-Gijón,John Sharian,358432,1082715.0
601,https://m.media-amazon.com/images/M/MV5BYzM2OG...,Kokuhaku,2010,15,106 min,"Drama, Thriller",7.8,A psychological thriller of a grieving mother ...,NaN,Tetsuya Nakashima,Takako Matsu,Yoshino Kimura,Masaki Okada,Yukito Nishii,35713,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('My name is Khan')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
352,https://m.media-amazon.com/images/M/MV5BMTUyMT...,My Name Is Khan,2010,12,165 min,Drama,8.0,An Indian Muslim man with Asperger's syndrome ...,50.0,Karan Johar,Shah Rukh Khan,Kajol,Sheetal Menon,Katie A. Keane,98575,4018695.0
374,https://m.media-amazon.com/images/M/MV5BYmVjND...,Kal Ho Naa Ho,2003,12,186 min,"Comedy, Drama, Musical",8.0,"Naina, an introverted, perpetually depressed g...",54.0,Nikkhil Advani,Preity Zinta,Shah Rukh Khan,Saif Ali Khan,Jaya Bachchan,63460,1787378.0
467,https://m.media-amazon.com/images/M/MV5BNDk3NT...,Call Me by Your Name,2017,15,132 min,"Drama, Romance",7.9,"In 1980s Italy, romance blossoms between a sev...",93.0,Luca Guadagnino,Armie Hammer,Timothée Chalamet,Michael Stuhlbarg,Amira Casar,212651,18095701.0
628,https://m.media-amazon.com/images/M/MV5BNjQ0NT...,The Curious Case of Benjamin Button,2008,12,166 min,"Drama, Fantasy, Romance",7.8,"Tells the story of Benjamin Button, a man who ...",70.0,David Fincher,Brad Pitt,Cate Blanchett,Tilda Swinton,Julia Ormond,589160,127509326.0
263,https://m.media-amazon.com/images/M/MV5BMmYyOT...,In the Name of the Father,1993,15,133 min,"Biography, Crime, Drama",8.1,A man's coerced confession to an I.R.A. bombin...,84.0,Jim Sheridan,Daniel Day-Lewis,Pete Postlethwaite,Alison Crosbie,Philip King,156842,25010410.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('deadpool')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
348,https://m.media-amazon.com/images/M/MV5BYzE5Mj...,Deadpool,2016,15,108 min,"Action, Adventure, Comedy",8.0,A wisecracking mercenary gets experimented on ...,65.0,Tim Miller,Ryan Reynolds,Morena Baccarin,T.J. Miller,Ed Skrein,902669,363070709.0
722,https://m.media-amazon.com/images/M/MV5BNjk1Nj...,Deadpool 2,2018,15,119 min,"Action, Adventure, Comedy",7.7,Foul-mouthed mutant mercenary Wade Wilson (a.k...,66.0,David Leitch,Ryan Reynolds,Josh Brolin,Morena Baccarin,Julian Dennison,478586,324591735.0
730,https://m.media-amazon.com/images/M/MV5BYTM3ZT...,Kingsman: The Secret Service,2014,15,129 min,"Action, Adventure, Comedy",7.7,A spy organisation recruits a promising street...,60.0,Matthew Vaughn,Colin Firth,Taron Egerton,Samuel L. Jackson,Michael Caine,590440,128261724.0
887,https://m.media-amazon.com/images/M/MV5BNjM0NT...,Guardians of the Galaxy Vol. 2,2017,12,136 min,"Action, Adventure, Comedy",7.6,The Guardians struggle to keep together as a t...,67.0,James Gunn,Chris Pratt,Zoe Saldana,Dave Bautista,Vin Diesel,569974,389813101.0
325,https://m.media-amazon.com/images/M/MV5BMjE1Nj...,Bajrangi Bhaijaan,2015,12,163 min,"Action, Adventure, Comedy",8.0,An Indian man with a magnanimous heart takes a...,NaN,Kabir Khan,Salman Khan,Harshaali Malhotra,Nawazuddin Siddiqui,Kareena Kapoor,72245,8178001.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('The kings speech')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
346,https://m.media-amazon.com/images/M/MV5BMzU5Mj...,The King's Speech,2010,12,118 min,"Biography, Drama, History",8.0,"The story of King George VI, his impromptu asc...",88.0,Tom Hooper,Colin Firth,Geoffrey Rush,Helena Bonham Carter,Derek Jacobi,639603,138797449.0
766,https://m.media-amazon.com/images/M/MV5BMjM1NT...,The Last King of Scotland,2006,15,123 min,"Biography, Drama, History",7.7,Based on the events of the brutal Ugandan dict...,74.0,Kevin Macdonald,James McAvoy,Forest Whitaker,Gillian Anderson,Kerry Washington,175355,17605861.0
235,https://m.media-amazon.com/images/M/MV5BZGJjYm...,Hotel Rwanda,2004,12,121 min,"Biography, Drama, History",8.1,"Paul Rusesabagina, a hotel manager, houses ove...",79.0,Terry George,Don Cheadle,Sophie Okonedo,Joaquin Phoenix,Xolani Mali,334320,23530892.0
877,https://m.media-amazon.com/images/M/MV5BODQ0M2...,Dark Waters,2019,12,126 min,"Biography, Drama, History",7.6,A corporate defense attorney takes on an envir...,73.0,Todd Haynes,Mark Ruffalo,Anne Hathaway,Tim Robbins,Bill Pullman,60408,NaN
373,https://m.media-amazon.com/images/M/MV5BODEyYm...,Cinderella Man,2005,12,144 min,"Biography, Drama, History",8.0,"The story of James J. Braddock, a supposedly w...",69.0,Ron Howard,Russell Crowe,Renée Zellweger,Craig Bierko,Paul Giamatti,176151,61649911.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('The help')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
347,https://m.media-amazon.com/images/M/MV5BMTM5OT...,The Help,2011,12A,146 min,Drama,8.0,An aspiring author during the civil rights mov...,62.0,Tate Taylor,Emma Stone,Viola Davis,Octavia Spencer,Bryce Dallas Howard,428521,169708112.0
327,https://m.media-amazon.com/images/M/MV5BMzUzND...,La La Land,2016,12A,128 min,"Comedy, Drama, Music",8.0,"While navigating their careers in Los Angeles,...",94.0,Damien Chazelle,Ryan Gosling,Emma Stone,Rosemarie DeWitt,J.K. Simmons,505918,151101803.0
87,https://m.media-amazon.com/images/M/MV5BYmY3Mz...,Drishyam,2013,12A,160 min,"Crime, Drama, Thriller",8.3,A man goes to extreme lengths to save his fami...,NaN,Jeethu Joseph,Mohanlal,Meena,Asha Sharath,Ansiba,30722,NaN
144,https://m.media-amazon.com/images/M/MV5BMTk4OD...,Warrior,2011,12A,140 min,"Action, Drama, Sport",8.2,The youngest son of an alcoholic former boxer ...,71.0,Gavin O'Connor,Tom Hardy,Nick Nolte,Joel Edgerton,Jennifer Morrison,435950,13657115.0
207,https://m.media-amazon.com/images/M/MV5BMTYzOT...,PK,2014,12A,153 min,"Comedy, Drama, Musical",8.1,An alien on Earth loses the only device he can...,NaN,Rajkumar Hirani,Aamir Khan,Anushka Sharma,Sanjay Dutt,Boman Irani,163061,10616104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search ('Casino Royale')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
368,https://m.media-amazon.com/images/M/MV5BMDI5ZW...,Casino Royale,2006,15,144 min,"Action, Adventure, Thriller",8.0,"After earning 00 status and a licence to kill,...",80.0,Martin Campbell,Daniel Craig,Eva Green,Judi Dench,Jeffrey Wright,582239,167445960.0
751,https://m.media-amazon.com/images/M/MV5BMWZiNj...,Skyfall,2012,12,143 min,"Action, Adventure, Thriller",7.7,James Bond's loyalty to M is tested when her p...,81.0,Sam Mendes,Daniel Craig,Javier Bardem,Naomie Harris,Judi Dench,630614,304360277.0
963,https://m.media-amazon.com/images/M/MV5BZjI0ZW...,Die Hard: With a Vengeance,1995,15,128 min,"Action, Adventure, Thriller",7.6,John McClane and a Harlem store owner are targ...,58.0,John McTiernan,Bruce Willis,Jeremy Irons,Samuel L. Jackson,Graham Greene,364420,100012499.0
725,https://m.media-amazon.com/images/M/MV5BNjRlZm...,Mission: Impossible - Fallout,2018,12,147 min,"Action, Adventure, Thriller",7.7,"Ethan Hunt and his IMF team, along with some f...",86.0,Christopher McQuarrie,Tom Cruise,Henry Cavill,Ving Rhames,Simon Pegg,291257,220159104.0
361,https://m.media-amazon.com/images/M/MV5BZDMxOG...,Blood Diamond,2006,15,143 min,"Adventure, Drama, Thriller",8.0,"A fisherman, a smuggler, and a syndicate of bu...",64.0,Edward Zwick,Leonardo DiCaprio,Djimon Hounsou,Jennifer Connelly,Kagiso Kuypers,499439,57366262.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Groundhog Day')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
396,https://m.media-amazon.com/images/M/MV5BZWIxNz...,Groundhog Day,1993,PG,101 min,"Comedy, Fantasy, Romance",8.0,A weatherman finds himself inexplicably living...,72.0,Harold Ramis,Bill Murray,Andie MacDowell,Chris Elliott,Stephen Tobolowsky,577991,70906973.0
835,https://m.media-amazon.com/images/M/MV5BY2E1YW...,The Purple Rose of Cairo,1985,PG,82 min,"Comedy, Fantasy, Romance",7.7,"In New Jersey in 1935, a movie character walks...",75.0,Woody Allen,Mia Farrow,Jeff Daniels,Danny Aiello,Irving Metzman,47102,10631333.0
685,https://m.media-amazon.com/images/M/MV5BMTkxMj...,Ghostbusters,1984,12A,105 min,"Action, Comedy, Fantasy",7.8,Three former parapsychology professors set up ...,71.0,Ivan Reitman,Bill Murray,Dan Aykroyd,Sigourney Weaver,Harold Ramis,355413,238632124.0
26,https://m.media-amazon.com/images/M/MV5BYmJmM2...,La vita è bella,1997,PG,116 min,"Comedy, Drama, Romance",8.6,When an open-minded Jewish librarian and his s...,59.0,Roberto Benigni,Roberto Benigni,Nicoletta Braschi,Giorgio Cantarini,Giustino Durano,623629,57598247.0
743,https://m.media-amazon.com/images/M/MV5BMTM4Nj...,Midnight in Paris,2011,12,96 min,"Comedy, Fantasy, Romance",7.7,While on a trip to Paris with his fiancée's fa...,81.0,Woody Allen,Owen Wilson,Rachel McAdams,Kathy Bates,Kurt Fuller,388089,56816662.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('JFK')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
400,https://m.media-amazon.com/images/M/MV5BYjYyOD...,JFK,1991,15,189 min,"Drama, History, Thriller",8.0,New Orleans District Attorney Jim Garrison dis...,72.0,Oliver Stone,Kevin Costner,Gary Oldman,Jack Lemmon,Walter Matthau,142110,70405498.0
268,https://m.media-amazon.com/images/M/MV5BMzRjZj...,Platoon,1986,15,120 min,"Drama, War",8.1,"Chris Taylor, a neophyte recruit in Vietnam, f...",92.0,Oliver Stone,Charlie Sheen,Tom Berenger,Willem Dafoe,Keith David,381222,138530565.0
7,https://m.media-amazon.com/images/M/MV5BNDE4OT...,Schindler's List,1993,15,195 min,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",94.0,Steven Spielberg,Liam Neeson,Ralph Fiennes,Ben Kingsley,Caroline Goodall,1213505,96898818.0
527,https://m.media-amazon.com/images/M/MV5BYTVjYW...,The Untouchables,1987,15,119 min,"Crime, Drama, Thriller",7.9,During the era of Prohibition in the United St...,79.0,Brian De Palma,Kevin Costner,Sean Connery,Robert De Niro,Charles Martin Smith,281842,76270454.0
820,https://m.media-amazon.com/images/M/MV5BZDkzOT...,Malcolm X,1992,15,202 min,"Biography, Drama, History",7.7,Biographical epic of the controversial and inf...,73.0,Spike Lee,Denzel Washington,Angela Bassett,Delroy Lindo,Spike Lee,85819,48169908.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('The Princess Bride')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
406,https://m.media-amazon.com/images/M/MV5BMGM4M2...,The Princess Bride,1987,PG,98 min,"Adventure, Family, Fantasy",8.0,"While home sick in bed, a young boy's grandfat...",77.0,Rob Reiner,Cary Elwes,Mandy Patinkin,Robin Wright,Chris Sarandon,393899,30857814.0
813,https://m.media-amazon.com/images/M/MV5BZDQzMG...,A Little Princess,1995,U,97 min,"Drama, Family, Fantasy",7.7,A young girl is relegated to servitude at a bo...,83.0,Alfonso Cuarón,Liesel Matthews,Eleanor Bron,Liam Cunningham,Rusty Schwimmer,32236,10019307.0
395,https://m.media-amazon.com/images/M/MV5BNWE4OT...,The Nightmare Before Christmas,1993,PG,76 min,"Animation, Family, Fantasy",8.0,"Jack Skellington, king of Halloween Town, disc...",82.0,Henry Selick,Danny Elfman,Chris Sarandon,Catherine O'Hara,William Hickey,300208,75082668.0
760,https://m.media-amazon.com/images/M/MV5BMTU2Nj...,Flipped,2010,PG,90 min,"Comedy, Drama, Romance",7.7,Two eighth-graders start to have feelings for ...,45.0,Rob Reiner,Madeline Carroll,Callan McAuliffe,Rebecca De Mornay,Anthony Edwards,81446,1752214.0
267,https://m.media-amazon.com/images/M/MV5BODJmY2...,Stand by Me,1986,15,89 min,"Adventure, Drama",8.1,"After the death of one of his friends, a write...",75.0,Rob Reiner,Wil Wheaton,River Phoenix,Corey Feldman,Jerry O'Connell,363401,52287414.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
search('Beauty and the Beast')

<ipython-input-26-1313b1598f13>:5: RuntimeWarning: invalid value encountered in double_scalars
  return np.dot(x,y)/(norm(x)*norm(y))

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
401,https://m.media-amazon.com/images/M/MV5BMzE5MD...,Beauty and the Beast,1991,U,84 min,"Animation, Family, Fantasy",8.0,A prince cursed to spend his days as a hideous...,95.0,Gary Trousdale,Kirk Wise,Paige O'Hara,Robby Benson,Jesse Corti,417178,218967620.0
976,https://m.media-amazon.com/images/M/MV5BN2JlZT...,The Little Mermaid,1989,U,83 min,"Animation, Family, Fantasy",7.6,A mermaid princess makes a Faustian bargain in...,88.0,Ron Clements,John Musker,Jodi Benson,Samuel E. Wright,Rene Auberjonois,237696,111543479.0
170,https://m.media-amazon.com/images/M/MV5BYzJjMT...,Tonari no Totoro,1988,U,86 min,"Animation, Family, Fantasy",8.2,When two girls move to the country to be near ...,86.0,Hayao Miyazaki,Hitoshi Takagi,Noriko Hidaka,Chika Sakamoto,Shigesato Itoi,291180,1105564.0
395,https://m.media-amazon.com/images/M/MV5BNWE4OT...,The Nightmare Before Christmas,1993,PG,76 min,"Animation, Family, Fantasy",8.0,"Jack Skellington, king of Halloween Town, disc...",82.0,Henry Selick,Danny Elfman,Chris Sarandon,Catherine O'Hara,William Hickey,300208,75082668.0
956,https://m.media-amazon.com/images/M/MV5BODkxNG...,Mulan,1998,U,88 min,"Animation, Adventure, Family",7.6,"To save her father from death in the army, a y...",71.0,Tony Bancroft,Barry Cook,Ming-Na Wen,Eddie Murphy,BD Wong,256906,120620254.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,https://m.media-amazon.com/images/M/MV5BYTIwND...,To Be or Not to Be,1942,U,99 min,"Comedy, War",8.2,"During the Nazi occupation of Poland, an actin...",86.0,Ernst Lubitsch,Carole Lombard,Jack Benny,Robert Stack,Felix Bressart,29915,NaN
341,https://m.media-amazon.com/images/M/MV5BMjA1Nz...,Her,2013,15,126 min,"Drama, Romance, Sci-Fi",8.0,"In a near future, a lonely writer develops an ...",90.0,Spike Jonze,Joaquin Phoenix,Amy Adams,Scarlett Johansson,Rooney Mara,540772,25568251.0
413,https://m.media-amazon.com/images/M/MV5BNjAzNz...,Being There,1979,12,130 min,"Comedy, Drama",8.0,"A simpleminded, sheltered gardener becomes an ...",83.0,Hal Ashby,Peter Sellers,Shirley MacLaine,Melvyn Douglas,Jack Warden,65625,30177511.0
617,https://m.media-amazon.com/images/M/MV5BYWUxZj...,Once,2007,15,86 min,"Drama, Music, Romance",7.8,A modern-day musical about a busker and an imm...,88.0,John Carney,Glen Hansard,Markéta Irglová,Hugh Walsh,Gerard Hendrick,110656,9439923.0
711,https://m.media-amazon.com/images/M/MV5BZGU2Ym...,To Have and Have Not,1944,PG,100 min,"Adventure, Comedy, Film-Noir",7.8,"During World War II, American expatriate Harry...",NaN,Howard Hawks,Humphrey Bogart,Lauren Bacall,Walter Brennan,Dolores Moran,31053,NaN

In [ ]:
import pandas as pd


df = pd.read_csv('imdb_top_1000.csv')


def search(query):
   
    results = df[df['Series_Title'].str.contains(query, case=False)]

    
    for i, result in results.head(10).iterrows():
        print(f"{i+1}. {result['Series_Title']} ({result['Released_Year']})")
        print(f"Rating: {result['IMDB_Rating']}, MetaRating: {result['Meta_score']}")
        print()

    relevance_feedback(results)

def relevance_feedback(results):
    
    relevant = []
    irrelevant = []
    for i, result in results.head(10).iterrows():
        feedback = input(f"Is result {i+1} relevant? (y/n)")
        if feedback.lower() == "y":
            relevant.append(result)
        else:
            irrelevant.append(result)


    if relevant:
        query += " ".join([result['Series_Title'] for result in relevant])
    if irrelevant:
        query += " -".join([result['Series_Title'] for result in irrelevant])

    search(query)

query = input("Enter a search query: ")
search(query)

416. Jaws (1975)
Rating: 8.0, MetaRating: 87.0

In [ ]:
import numpy as np

# Define a function to calculate the NDCG@50 score
def ndcg_at_k(r, k=50):
    # Create a vector of discounted gains for the relevant documents
    gains = 2 ** r - 1
    discounts = np.log2(np.arange(len(r)) + 2)
    dcg = np.sum(gains[:k] / discounts[:k])

    # Create a vector of ideal discounted gains for the relevant documents
    sorted_gains = sorted(gains, reverse=True)
    ideal_dcg = np.sum(sorted_gains[:k] / discounts[:k])

    # Calculate the NDCG@k score
    if ideal_dcg == 0:
        return 0
    else:
        return dcg / ideal_dcg

# Define a function to evaluate the ranking system using NDCG@50
def evaluate_ranking_system(rankings, relevant_documents):
    # Create a binary relevance vector for the relevant documents
    relevance = np.zeros(len(rankings))
    for i, doc in enumerate(rankings):
        if doc in relevant_documents:
            relevance[i] = 1

    # Calculate the NDCG@50 score
    ndcg = ndcg_at_k(relevance, k=50)

    # Return the NDCG@50 score
    return ndcg